### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by GunnarHorve** [conru/painter#4]
When creating "File-->Exit", processes continue running on Task Manager invisibly.

**Comment by asleeponduty** [comment]
With the latest codebase, the project continues to run even when the main window is closed. 

Previously, the program could be terminated by closing the debug command windows. Unfortunately, these windows now only open when the "-debug" argument is passed to the program.

**Comment by asleeponduty** [comment]
It looks like that this is a Qt thing. 
I can't tell how to use it yet, but this is required to be declared in the main qt window:
`Qt::WA_QuitOnClose`
  
Also, calling this function will cause the Qt app to close:
`QCoreApplication::quit()`
